#!/bin/bash
#
# Align generated K8s base types with @openshift/api-types
#
# After OpenAPI generation, this script:
# 1. Replaces ObjectMeta / ManagedFieldsEntry models with thin shims that
#    alias to @openshift/api-types (ObjectMetadata / ManagedFieldsEntry)
# 2. Converts remaining Date timestamp fields under src/generated to string
#    (Kubernetes APIs return ISO 8601 strings; Console SDK uses string)
#
# Usage: ./scripts/align-k8s-base-types.sh
#        npm run align:k8s-base
#
# Safe to run multiple times (idempotent).
#

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
GENERATED_DIR="$PROJECT_ROOT/src/generated"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Aligning K8s base types${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

write_object_meta_shim() {
  local file="$1"
  local type_name="$2"
  local relative_path="${file#$PROJECT_ROOT/}"

  mkdir -p "$(dirname "$file")"
  cat > "$file" << EOF
/* tslint:disable */
/* eslint-disable */
/**
 * Shim: aliases generated ObjectMeta to @openshift/api-types ObjectMetadata.
 * Kept for OpenAPI generator FromJSON/ToJSON call sites.
 * Do not edit manually — regenerated by scripts/align-k8s-base-types.sh
 */
import type { ObjectMetadata } from '@openshift/api-types';

export type ${type_name} = ObjectMetadata;

export function instanceOf${type_name}(value: object): value is ObjectMetadata {
  return true;
}

export function ${type_name}FromJSON(json: any): ObjectMetadata {
  return ${type_name}FromJSONTyped(json, false);
}

export function ${type_name}FromJSONTyped(json: any, _ignoreDiscriminator: boolean): ObjectMetadata {
  return json;
}

export function ${type_name}ToJSON(value?: ObjectMetadata | null): any {
  return ${type_name}ToJSONTyped(value, false);
}

export function ${type_name}ToJSONTyped(value?: ObjectMetadata | null, _ignoreDiscriminator: boolean = false): any {
  return value;
}
EOF

  echo -e "${GREEN}  ✓ ${relative_path}: ObjectMeta shim → ObjectMetadata${NC}"
}

write_managed_fields_shim() {
  local file="$1"
  local type_name="$2"
  local relative_path="${file#$PROJECT_ROOT/}"

  mkdir -p "$(dirname "$file")"
  cat > "$file" << EOF
/* tslint:disable */
/* eslint-disable */
/**
 * Shim: aliases generated ManagedFieldsEntry to @openshift/api-types ManagedFieldsEntry.
 * Kept for OpenAPI generator FromJSON/ToJSON call sites.
 * Do not edit manually — regenerated by scripts/align-k8s-base-types.sh
 */
import type { ManagedFieldsEntry } from '@openshift/api-types';

export type ${type_name} = ManagedFieldsEntry;

export function instanceOf${type_name}(value: object): value is ManagedFieldsEntry {
  return true;
}

export function ${type_name}FromJSON(json: any): ManagedFieldsEntry {
  return ${type_name}FromJSONTyped(json, false);
}

export function ${type_name}FromJSONTyped(json: any, _ignoreDiscriminator: boolean): ManagedFieldsEntry {
  return json;
}

export function ${type_name}ToJSON(value?: ManagedFieldsEntry | null): any {
  return ${type_name}ToJSONTyped(value, false);
}

export function ${type_name}ToJSONTyped(value?: ManagedFieldsEntry | null, _ignoreDiscriminator: boolean = false): any {
  return value;
}
EOF

  echo -e "${GREEN}  ✓ ${relative_path}: ManagedFieldsEntry shim → ManagedFieldsEntry${NC}"
}

echo -e "${BLUE}Writing ObjectMeta / ManagedFieldsEntry shims...${NC}"

write_object_meta_shim \
  "$GENERATED_DIR/kubernetes/models/IoK8sApimachineryPkgApisMetaV1ObjectMeta.ts" \
  "IoK8sApimachineryPkgApisMetaV1ObjectMeta"

write_managed_fields_shim \
  "$GENERATED_DIR/kubernetes/models/IoK8sApimachineryPkgApisMetaV1ManagedFieldsEntry.ts" \
  "IoK8sApimachineryPkgApisMetaV1ManagedFieldsEntry"

write_object_meta_shim \
  "$GENERATED_DIR/kubevirt/models/K8sIoApimachineryPkgApisMetaV1ObjectMeta.ts" \
  "K8sIoApimachineryPkgApisMetaV1ObjectMeta"

write_managed_fields_shim \
  "$GENERATED_DIR/kubevirt/models/K8sIoApimachineryPkgApisMetaV1ManagedFieldsEntry.ts" \
  "K8sIoApimachineryPkgApisMetaV1ManagedFieldsEntry"

write_object_meta_shim \
  "$GENERATED_DIR/containerized-data-importer/models/V1ObjectMeta.ts" \
  "V1ObjectMeta"

write_managed_fields_shim \
  "$GENERATED_DIR/containerized-data-importer/models/V1ManagedFieldsEntry.ts" \
  "V1ManagedFieldsEntry"

echo ""
echo -e "${BLUE}Converting remaining Date timestamp fields to string...${NC}"

FIXED_COUNT=0

fix_timestamp_file() {
  local file="$1"
  local relative_path="${file#$PROJECT_ROOT/}"
  local changed=false

  # Skip runtime helpers (uses Date for query encoding, not API fields)
  if [[ "$file" == *"/runtime.ts" ]]; then
    return 0
  fi

  if grep -qE '(\?: Date;|: Date;|\[key: string\]: Date;|@type \{Date\}|new Date\(json\[|toISOString\(\))' "$file"; then
    # Optional and required Date field annotations → string
    sed -i '' \
      -e 's/\?: Date;/\?: string;/g' \
      -e 's/: Date;/: string;/g' \
      -e 's/\[key: string\]: Date;/[key: string]: string;/g' \
      -e 's/@type {Date}/@type {string}/g' \
      -e 's/@type {{ \[key: string\]: Date; }}/@type {{ [key: string]: string; }}/g' \
      "$file"

    # FromJSON Date parsing → passthrough
    if grep -q "(new Date(json\[" "$file"; then
      sed -i '' "s/(new Date(json\['\([^']*\)'\]))/json['\1']/g" "$file"
    fi

    # ToJSON toISOString → passthrough
    if grep -q "toISOString()" "$file"; then
      sed -i '' "s/((value\['\([^']*\)'\])\.toISOString())/value['\1']/g" "$file"
    fi

    echo -e "${GREEN}  ✓ ${relative_path}: Date types → string${NC}"
    changed=true
  fi

  if [ "$changed" = true ]; then
    FIXED_COUNT=$((FIXED_COUNT + 1))
  fi
}

while IFS= read -r -d '' file; do
  fix_timestamp_file "$file"
done < <(find "$GENERATED_DIR" -type f -name '*.ts' -print0)

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Shims written (6 files)${NC}"
if [ "$FIXED_COUNT" -gt 0 ]; then
  echo -e "${GREEN}Fixed timestamp types in ${FIXED_COUNT} file(s)${NC}"
else
  echo -e "${YELLOW}No additional Date→string fixes needed${NC}"
fi
echo -e "${GREEN}========================================${NC}"
